### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by zwj7181** [kisixing/LianMp#1]
# 项目计划及改进

- [ ] 1、 接口超时处理（对于一些查询可能会超过5s）
- [ ] 2、提示消息（toast），统一放到一个const类，是否支持多语言
- [x] 3、路由带参数的处理封装（考虑进入一些详情页的标准处理）
- [ ] 4、通过model返回接口结果的页面获取【已有方法】
- [ ] 5、返回按钮再 pagewrapper组件的封装，及返回逻辑
- [ ] 6、标准页实现 （验证码登录、公众号登录）
- [ ] 7、页面跳转的统一处理，最好可以抽离出配置
- [ ] 8、表单页，renderitem方法 抽离，表单配置最好不要放到model中（可免编译修改的文件）
- [ ] 9、列表页封装， 实现2~3三层json的解析配置，默认增加onclick的事件
- [ ] 10、提交按钮封装 重复点击控制 
- [ ] 11、表单，自动缓存机制 处理。
- [ ] 12、独立页的通信处理。
- [ ] 13、未完成的组件开发
